### ISSUE TITLE
New 2.x major release version

### ISSUE THREAD

**Issue by starksm64** [arquillian/arquillian-container-jetty#110]
There should be a new release that bumps the major version to 2.x and aligns with the EE10 dependencies. This issue will track the required changes.

**Comment by olamy** [comment]
sounds reasonable.
what about first cut a last 1.x release, move the code to a branch 1.x then bump master to 2.x and dependencies as well.
I can do almost everything except cut a last release ;)

**Comment by olamy** [comment]
@starksm64 feel free to cut the release. I will look after the other parts. thanks!

**Comment by manovotn** [comment]
Hi @olamy, seeing as you contributed the v11 of embedded container, is it EE 10 ready? I can see that Jetty 11 still uses CDI 3 and trying to update the CDI API as well as Weld impl, I am getting errors from within Jetty bootstrap.
Also, is v11 only supposed to work with junit5?

**Comment by joakime** [comment]
EE10 support is scheduled for Jetty 12 (actively being developed, no release yet)

**Comment by chengfang** [comment]
2.0.0.Final is released on 2023-08-20: https://github.com/arquillian/arquillian-container-jetty/releases/tag/2.0.0.Final

**Comment by olamy** [comment]
we can close this as done :)

**Comment by hantsy** [comment]
Tried to add a ee9-jetty12 support to my example project, failed. https://github.com/hantsy/jakartaee9-servlet-starter-boilerplate/pull/166

Check the build stack on github actions: https://github.com/hantsy/jakartaee9-servlet-starter-boilerplate/actions/runs/6595413820/job/17920411770
