### ISSUE TITLE
Create 1.0.0.Final release and then create 1.0 branch

### ISSUE THREAD

**Issue by starksm64** [arquillian/arquillian-container-jetty#111]
As a prerequisite to #110 , we should create a 1.0.0.Final release and create a 1.0 branch from that tag so we can move the main to 2.0 and EE10 dependencies.

**Comment by starksm64** [comment]
This has been created.

**Comment by starksm64** [comment]
A 1.0 branch for future bug fixes/enhancements has been create from the 1.0.0.Final tag.

**Comment by hantsy** [comment]
@starksm64 Jetty 12 GA is available, please publish a new version for it(both EE 9 and EE 10).

**Comment by chengfang** [comment]
@hantsy pls see https://github.com/arquillian/arquillian-container-jetty/issues/110
