### ISSUE TITLE
Jetty 9 Protocol Description should be "servlet 3.1"

### ISSUE THREAD

**Issue by joakime** [arquillian/arquillian-container-jetty#7]
Jetty 9 Protocol Description falsely states "servlet 3.0" that is incorrect.

Jetty 7 is "servlet 2.5"
Jetty 8 is "servlet 3.0"
Jetty 9 is "servlet 3.1"

**Comment by joakime** [comment]
@starksm64 this is still a valid issue in arquillian core.

https://github.com/arquillian/arquillian-container-jetty/blob/4ed9fe5e98a35409b31bb65f4f8ea8089c5b6e11/jetty-embedded-9/src/main/java/org/jboss/arquillian/container/jetty/embedded_9/JettyEmbeddedContainer.java#L126-L131

**Comment by starksm64** [comment]
So the arquillian-core has not added a protocol specific to the 3.1 servlet spec, so 3.0 is the closet match.
