### ISSUE TITLE
Create new Jetty container team and add members

### ISSUE THREAD

**Issue by starksm64** [arquillian/arquillian-container-jetty#88]
I created a https://github.com/orgs/arquillian/teams/container-jetty team, but I don't have access to add the arquillian-container-jetty repo to it.

@bartoszmajsak can you add the repo to the group and add @joakime @olamy as members?
We should setup more teams with members from the associated community for key repos like Jetty.

**Comment by olamy** [comment]
awesome! Thanks guys!

**Comment by bartoszmajsak** [comment]
@starksm64 invites sent

**Comment by starksm64** [comment]
Thanks @bartoszmajsak , sorry for the intrusion.

**Comment by bartoszmajsak** [comment]
> Thanks @bartoszmajsak , sorry for the intrusion.

No problem at all @starksm64. I just wanted to make you aware I might be somewhat slow with the responses. Once I'm back let's put some plan for teams together. Have a great weekend!

**Comment by starksm64** [comment]
The arquillian-container-jetty repo has been added to the container-jetty team.

**Comment by olamy** [comment]
it looks I cannot push https://github.com/arquillian/arquillian-container-jetty/pull/90

**Comment by starksm64** [comment]
Check another PR now. It looks like I did not have the team permissions correct.

**Comment by olamy** [comment]
@starksm64 all good! Thanks!
