### ISSUE TITLE
Jetty 11 embedded exception: ArquillianServletRunnerEE9 not found

### ISSUE THREAD

**Issue by hantsy** [arquillian/arquillian-container-jetty#93]
I have created a [Serlvet5/Jakarta EE 9 template project](https://github.com/hantsy/jakartaee9-servlet-starter-boilerplate) which demos the latest web related specs in a servlet container, I found this arquillian-container-jetty added Jetty 11 support finally, it is great news.

But I tried to add a Maven profile to run the arquillian tests on `jetty11 embedded`, it failed and I got the following exception info.

```bash
java.lang.IllegalArgumentException: ArquillianServletRunnerEE9 not found.
Could not determine ContextRoot from ProtocolMetadata, please contact DeployableContainer developer.
```

My template project configured testing sample with Jaxrs, servlet, CDI, etc, I have created a [branch/PR for Jetty11 with a new Maven profile `arq-jetty-embedded`](https://github.com/hantsy/jakartaee9-servlet-starter-boilerplate/pull/74).

BTW, I also configured a jetty-external profile and make sure the project work on a external Jetty server by maven plugin.

**Comment by joakime** [comment]
There's only ever been 1 release of arquillian-jetty-embedded-11

https://search.maven.org/artifact/org.jboss.arquillian.container/arquillian-jetty-embedded-11

Version 1.0.0.CR4

Is that what you are using with Arquilian 1.7.0.Alpha10?

**Comment by joakime** [comment]
There's never been a release that supports external Jetty 11 (using jetty-home).

**Comment by Milton-Ch** [comment]
@joakime Yes, I'm using 1.0.0.CR4 version with Jetty 11.0.9 and Arquillian 1.7.0.Alpha10.
BTW, in my case, I see not found for all different servlets and endpoints.
![image](https://user-images.githubusercontent.com/86965029/168087784-1965dfd6-db33-46c4-a6bc-63d80eacc239.png)
I included JSP dependency and it works, but for endpoints it doesn't.

**Comment by hantsy** [comment]
Not sure if it needs extra config, I have checked the testing codes of embedded-jetty adapter and configured my sample project, it did not work as expected.

**Comment by olamy** [comment]
you should add this dependencies to get some logs:
```
                <dependency>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-simple</artifactId>
                    <version>1.7.36</version>
                    <scope>test</scope>
                </dependency>
```
as you have added faces you will need websocket
```
                <dependency>
                    <groupId>org.eclipse.jetty.websocket</groupId>
                    <artifactId>websocket-jakarta-server</artifactId>
                    <scope>test</scope>
                </dependency>
```
and as there is some jsp need you mush add this one as well
```
                <dependency>
                    <groupId>org.eclipse.jetty</groupId>
                    <artifactId>apache-jsp</artifactId>
                    <scope>test</scope>
                </dependency>
```

**Comment by olamy** [comment]
look at this PR https://github.com/hantsy/jakartaee9-servlet-starter-boilerplate/pull/92
but there is still an issue with 
```
    @Inject
    GreetingService service;
```
which is still null I will look at this.

**Comment by olamy** [comment]
fixed with https://github.com/arquillian/arquillian-container-jetty/pull/108

**Comment by hantsy** [comment]
I tried to add `arquillian-testenricher-cdi-jakarta` or  `arquillian-testenricher-resource-jakarta` to my original PR(used the 1.0.0-CR4), there still is a failure of GreetingServiceTests which caused by NPE exception.

**Comment by Milton-Ch** [comment]
@olamy I installed manually this dependency initially:
```
<dependency>
	<groupId>org.jboss.arquillian.container</groupId>
	<artifactId>arquillian-jetty-embedded-11</artifactId>
	<version>1.0.0.Final-SNAPSHOT</version>
	<scope>test</scope>
</dependency>
```
Then based on @hantsy's comments, I also added:
```
<dependency>
	<groupId>org.jboss.arquillian.testenricher</groupId>
	<artifactId>arquillian-testenricher-resource-jakarta</artifactId>
</dependency>
<dependency>
	<groupId>org.jboss.arquillian.testenricher</groupId>
	<artifactId>arquillian-testenricher-cdi-jakarta</artifactId>
</dependency>
```

I also tested these dependencies:
https://github.com/arquillian/arquillian-container-jetty/issues/93#issuecomment-1126650995

![image](https://user-images.githubusercontent.com/86965029/168896385-8f6372cd-bd73-4e0e-b8ac-43efe2aac41c.png)

**Comment by olamy** [comment]
yes because this will need few other pom tricks to exclude some dependencies.
the best and easiest will be to have another 1.0.0.xxx release
maybe @starksm64 could cut one? ;)

**Comment by starksm64** [comment]
Ok, I'll do #111  tomorrow

**Comment by hantsy** [comment]
@olamy I added a new profile to my example project to demo Jetty 12+ EE 9, it throws the exception again, check the exception stack: https://github.com/hantsy/jakartaee9-servlet-starter-boilerplate/actions/runs/5926848264/job/16069070688

And the config for Jetty 12 and EE 9, https://github.com/hantsy/jakartaee9-servlet-starter-boilerplate/blob/arq-jetty-12/pom.xml#L488-L576

**Comment by divjad---** [comment]
Hello,

I am facing a similar issue. I am using a custom class that extends `DeployableContainer`. Before updating my project to Jakarta EE 9, the tests were working fine. I am confident that my deployable container is being utilized because if I change the protocol to Servlet 3.0, I encounter an issue where the "protocolDefinition" is null.

**Comment by olamy** [comment]
> Hello,
> 
> I am facing a similar issue. I am using a custom class that extends `DeployableContainer`. Before updating my project to Jakarta EE 9, the tests were working fine. I am confident that my deployable container is being utilized because if I change the protocol to Servlet 3.0, I encounter an issue where the "protocolDefinition" is null.

do you mean jetty 12? or Jetty 11?

**Comment by divjad---** [comment]
I am using Jetty 11.

**Comment by olamy** [comment]
> I am using Jetty 11.

Can you test Jetty 12 EE9?
